[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "mirror chief stadium mountain aspect girl nation salt common inhale again myth space renew hamster vehicle slight laugh human shift tool still bless pretty"
